# Generated by Django 5.2 on 2025-04-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickle_app', '0003_alter_player_options_rename_name_player_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='experience_years',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Years of pickleball experience', max_digits=4),
        ),
    ]
